<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="EPUAKYIW0056" name="Default test" tests="1" failures="1" timestamp="23 Oct 2013 04:59:46 GMT" time="0.552" errors="0">
  <testcase name="test" time="0.542" classname="test.java.CorsTest">
    <failure type="com.amazonaws.services.s3.model.AmazonS3Exception" message="Status Code: 403, AWS Service: Amazon S3, AWS Request ID: 1382504380526757bc74284, AWS Error Code: InvalidAccessKeyId, AWS Error Message: The Access Key Id you provided does not exist in our records.">
      <![CDATA[com.amazonaws.services.s3.model.AmazonS3Exception: Status Code: 403, AWS Service: Amazon S3, AWS Request ID: 1382504380526757bc74284, AWS Error Code: InvalidAccessKeyId, AWS Error Message: The Access Key Id you provided does not exist in our records., S3 Extended Request ID: storage1-1.s3for.me
	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:725)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:388)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:249)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3104)
	at com.amazonaws.services.s3.AmazonS3Client.setBucketCrossOriginConfiguration(AmazonS3Client.java:1793)
	at test.java.CorsTest.test(CorsTest.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- test -->
</testsuite> <!-- Default test -->
